### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by malthejorgensen** [malthejorgensen/repx#1]
Must have
-------------

- [x] stdin/stdout handling
- [x] file input
- [ ] file output
- [ ] in-place file transformation
- [x] pip installable package
- [ ] PyPI installable package
- [ ] tests (locally)
- [ ] TravisCI tests

Maybe?
---------

- Recursive flag, e.g. `prex /World/Universe/ -r .` (possible using .gitignore as well?)

Inspiration
------------
Great command line tools

* ack (and ag/silver searcher)
* [rq](https://github.com/dflemstr/rq)
* [jq](https://stedolan.github.io/jq/)
